let User,CustomErrorHandler;_92d‍.x([["default",()=>_92d‍.o]]);_92d‍.w("../models",[["User",["User"],function(v){User=v}]]);_92d‍.w("../services/CustomErrorHandler",[["default",["CustomErrorHandler"],function(v){CustomErrorHandler=v}]]);


const userController = {
  async me(req, res, next) {

    try {
      //Getting user detail from DB
      const user = await User.findOne({ _id: req.user._id }).select('-password -updatedAt -__v');
      if(!user){
        return next(CustomErrorHandler.notFound());
      }
      return res.json(user);
    } catch (err) {
        return next(err);
    }
  },
};

_92d‍.d(userController);
